sudo: required
addons:
    chrome: stable
language: node_js
node_js:
  - "10.10"
branches:
  only:
  -master
before_script:
  -npm install -g javascript
 script:
  -npm install
  -ng build --aot --prod